name: rebellion
description: A linter for Flutter's ARB files. Analyze ARB files and find possible issues, find missing translations and sort ARB files
version: 0.1.1
repository: https://github.com/rebelappstudio/rebellion

executables:
  rebellion: main

topics:
  - localization
  - l10n
  - lints
  - analysis
  - analyzer

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  path: ^1.9.1
  yaml: ^3.1.3
  analyzer: ^7.1.0
  json_events: ^1.2.2
  file: ^7.0.1
  meta: ^1.16.0
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
