name: rebellion
description: A sample command-line application.
version: 1.0.0
publish: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  petitparser: ^6.0.2
  dart_openai: ^5.1.0
  yaml: ^3.1.2
  http: ^1.2.1
  xml: ^6.5.0
  analyzer: ^6.5.0
  json_events: ^1.2.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
