name: rebellion
description: A linter for Flutter's ARB files
version: 0.0.1
publish: none
repository: https://github.com/rebelappstudio/rebellion
# homepage: https://github.com/my_org/my_repo

topics:
  - localization
  - l10n
  - lints
  - analysis
  - analyzer

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0
  yaml: ^3.1.2
  analyzer: ^6.5.0
  json_events: ^1.2.2
  file: ^7.0.0
  meta: ^1.15.0
  equatable: ^2.0.5
  http: ^1.2.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
