name: plural_rules_generator
description: A sample command-line application.
version: 1.0.0
publish: none

environment:
  sdk: ^3.5.1

dependencies:
  http: ^1.2.1
  xml: ^6.5.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
