name: Pull requests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze-test:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: cd packages/plural_rules_generator/ && dart pub get && cd ../..

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Setup lcov
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Test and generate coverage report
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
          lcov --remove coverage/lcov.info 'lib/src/message_parser/*' 'lib/src/generated/*' -o coverage/new_lcov.info

      - name: Upload code coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/new_lcov.info
          fail_ci_if_error: true
