# Download latest plural rules, generate dart file and create a PR with changes
name: Get latest plural rules

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1 # At 06:00 on Monday

jobs:
  analyze-test:
    name: Run plurals generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: cd packages/plural_rules_generator && dart pub get && cd ../..

      - name: Generate plural rules
        run: dart packages/plural_rules_generator/bin/plural_rules_generator.dart ./lib/src/generated/plural_rules.dart

      - name: Create pull request with changes (if any)
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update plural rules"
          title: "[automated] Update plural rules"
